### PR TITLE
initial commit - answered ?s to assignment

### PR DESCRIPTION
**Pull request by fncischen**
@ryanboris

### CODE REVIEW

**Comment by fncischen** [comment]
@ryanboris : created a visual diagram based on the instructions provided by Github Repository so I can visualize how to structure components, data, and state throughout ecosystem.

**Comment by fncischen** [comment]
Next step -> Stretch Goal

**Comment by secantsquared** [comment]
> @ryanboris : created a visual diagram based on the instructions provided by Github Repository so I can visualize how to structure components, data, and state throughout ecosystem.

THIS IS EXCELLENT - great technique

**Review by secantsquared — APPROVED** [review]
Looks great - MVP hit, and continue to stretch if you like until our meeting time. 

GREAT WORK - love the organization and how you approached the entire project as a whole at first.

**Comment by secantsquared** [comment]
@fncischen I am going to leave the close and merge to your discretion just in case you are still doing things with this.

**Comment by fncischen** [comment]
@ryanboris , thank you for the warm comments! Super appreciated! 👍 

I've added a "pseudo" Higher Order Component for the LogIn Page.

**Pull request merged**
